### ISSUE TITLE
version 1.4.2

### ISSUE THREAD

**Issue by wtto00** [wtto00/html2canvas#5]
```shell
pnpm add @wtto00/html2canvas@^1.4.2
```

### support `object-fit` of `<img/>`
- https://github.com/niklasvh/html2canvas/issues/2811
- https://github.com/niklasvh/html2canvas/issues/2541
- https://github.com/niklasvh/html2canvas/issues/2442
- https://github.com/niklasvh/html2canvas/issues/1064
- https://github.com/niklasvh/html2canvas/issues/725
- https://github.com/niklasvh/html2canvas/issues/3072

**Comment by wwj12r** [comment]
thx bro
